### ISSUE TITLE
Please provide minimum glusterfs version for the install

### ISSUE THREAD

**Issue by aldemira** [olli-ai/glusterfs-subdir-external-provisioner#2]
Hi there first of all thanks for this project. Saved me from the headache of a heketi setup. The trouble I run into was, I tried installing default debian 10 (buster) supplied glusterfs-client (5.5) and I had all sorts of different/weird errors. Afterwards, I switched to version 9.2 from official glusterfs repository and everything works fine so far.

**Comment by aure-olli** [comment]
Hi, happy to help :)
Yeah debian, I remember the nightmare of having always outdated packages XD OK I'll add a few lines to warn about the version that should be used. I've only tested with 7 and 9 I think, so let's say 7 will be the minimum. This is probably a problem of kubernetes, since the GlusterFS volume is mounted in the pod.
